<?php
declare(strict_types=1);

/** @var Elogic\AdminCrud\Block\CRUD $block */
/*$collection = $block->getAllStores();
$collection->getSelect()
    ->joinLeft(
        'flush795_shops_addresses',
        'flush795_shops_addresses.shop_address_id = main_table.shop_address_id',
        '*'
    );
$collection->getSelect()
    ->joinLeft(
        'flush_shop_work_schedule',
        'flush_shop_work_schedule.shop_schedule_id = main_table.shop_schedule_id',
        '*'
    );
var_dump($collection->getData());*/
?>

<p>Hello World!</p>


